import { useEffect, useMemo, useRef, useState, type CSSProperties } from 'react';
import { onAuthStateChanged } from 'firebase/auth';
import { BarChart3, BookOpen, CalendarDays, Check, ChevronLeft, ChevronRight, Clock3, CloudUpload, Download, Home, LogOut, Moon, Plus, Settings as SettingsIcon, Sparkles, Trash2, Upload, X } from 'lucide-react';
import { Cell, ResponsiveContainer, BarChart, Bar, XAxis, Tooltip } from 'recharts';
import { auth, firebaseConfigured, logout, signIn, type AuthUser } from './firebase';
import { clearUser, id, put, remove, restore, userData } from './db';
import { dateISO, overall, subjectStats } from './math';
import { extractTimetable } from './gemini';
import { makeBackup, parseBackup } from './backup';
import type { Attendance, AttendanceStatus, BackupPayload, Settings, Subject, TimetableEntry } from './types';
import { DAYS } from './types';

type Page = 'home' | 'attendance' | 'calendar' | 'timetable' | 'statistics' | 'settings';
const colors = ['#6d5dfc', '#20c997', '#ff8d5c', '#e95d9a', '#3989ff', '#e0a526'];
const todayDay = () => DAYS[(new Date().getDay() + 6) % 7];
const initialSubject = (uid: string, target: number): Subject => ({ id: id(), uid, name: '', code: '', teacher: '', room: '', color: colors[0], target, createdAt: new Date().toISOString() });
function Modal({ children, onClose }: { children: React.ReactNode, onClose: () => void }) { return <div className="scrim" role="dialog" aria-modal="true"><div className="modal"><button className="icon close" onClick={onClose}><X /></button>{children}</div></div> }
function App() {
  const [user, setUser] = useState<AuthUser | null>(null), [loading, setLoading] = useState(true), [page, setPage] = useState<Page>('home');
  const [subjects, setSubjects] = useState<Subject[]>([]), [records, setRecords] = useState<Attendance[]>([]), [table, setTable] = useState<TimetableEntry[]>([]), [settings, setSettings] = useState<Settings | null>(null);
  const [modal, setModal] = useState<'subject' | 'entry' | 'import' | 'backup' | 'restore' | 'clear' | null>(null), [editSubject, setEditSubject] = useState<Subject | null>(null), [editEntry, setEditEntry] = useState<TimetableEntry | null>(null), [toast, setToast] = useState('');
  const uid = user?.uid ?? '';
  const flash = (m: string) => { setToast(m); window.setTimeout(() => setToast(''), 3500) };
  useEffect(() => { if (!auth) { setLoading(false); return } return onAuthStateChanged(auth, async u => { setUser(u); setLoading(false); if (u) { await put('users', { uid: u.uid, email: u.email ?? '', name: u.displayName ?? '', photoURL: u.photoURL ?? '', updatedAt: new Date().toISOString() }); const d = await userData(u.uid); setSubjects(d.subjects); setRecords(d.attendance); setTable(d.timetable); setSettings(d.settings) } }) }, []);
  useEffect(() => { const t = settings?.theme ?? 'system'; document.documentElement.dataset.theme = t; }, [settings?.theme]);
  const reload = async () => { if (!uid) return; const d = await userData(uid); setSubjects(d.subjects); setRecords(d.attendance); setTable(d.timetable); setSettings(d.settings) };
  const saveSubject = async (s: Subject) => { await put('subjects', s); await reload(); setModal(null); flash('Subject saved') };
  const deleteSubject = async (s: Subject, history: boolean) => { if (!confirm(`Delete ${s.name}?`)) return; await remove('subjects', s.id); if (history) await Promise.all(records.filter(r => r.subjectId === s.id).map(r => remove('attendance', r.id))); await reload(); flash(history ? 'Subject and history deleted' : 'Subject deleted; attendance history preserved') };
  const mark = async (subjectId: string, status: AttendanceStatus, date = dateISO(), sessionId = 'manual') => { const old = records.find(r => r.subjectId === subjectId && r.date === date && r.sessionId === sessionId); const item: Attendance = { id: old?.id ?? id(), uid, subjectId, date, sessionId, status, updatedAt: new Date().toISOString() }; await put('attendance', item); await reload(); flash(status === 'unmarked' ? 'Attendance cleared' : `Marked ${status}. Undo?`) };
  const saveEntry = async (e: TimetableEntry) => { await put('timetable', e); await reload(); setModal(null); flash('Timetable saved') };
  const stats = useMemo(() => overall(subjects, records), [subjects, records]);
  const navigate = (p: Page) => setPage(p);
  if (loading) return <div className="center"><div className="spinner" />Loading your attendance…</div>;
  if (!user) return <Login />;
  const nav = [['home', Home, 'Home'], ['attendance', Check, 'Attendance'], ['calendar', CalendarDays, 'Calendar'], ['timetable', Clock3, 'Timetable'], ['statistics', BarChart3, 'Statistics'], ['settings', SettingsIcon, 'Settings']] as const;
  return <div className="app"><aside><Brand /><nav>{nav.map(([p, I, l]) => <button key={p} className={page === p ? 'active' : ''} onClick={() => navigate(p)}><I /><span>{l}</span></button>)}</nav><Profile user={user} /></aside><main><header><div><p className="eyebrow">{new Date().toLocaleDateString(undefined, { weekday: 'long', month: 'long', day: 'numeric' })}</p><h1>{page === 'home' ? 'Good to see you' : page[0].toUpperCase() + page.slice(1)}</h1></div><button className="avatar" onClick={() => navigate('settings')}><img src={user.photoURL ?? ''} alt="Profile" /></button></header>
    {page === 'home' && <Dashboard subjects={subjects} records={records} table={table} stats={stats} onMark={mark} onAdd={() => { setEditSubject(initialSubject(uid, settings?.defaultTarget ?? 75)); setModal('subject') }} onEdit={s => { setEditSubject(s); setModal('subject') }} onNav={navigate} />}
    {page === 'attendance' && <AttendancePage subjects={subjects} records={records} onMark={mark} />} {page === 'calendar' && <CalendarPage subjects={subjects} records={records} onMark={mark} />} {page === 'timetable' && <TimetablePage subjects={subjects} table={table} onAdd={() => { setEditEntry(blankEntry(uid)); setModal('entry') }} onEdit={e => { setEditEntry(e); setModal('entry') }} onDelete={async e => { if (confirm('Delete this class?')) { await remove('timetable', e.id); await reload() } }} onImport={() => setModal('import')} />} {page === 'statistics' && <Statistics subjects={subjects} records={records} stats={stats} />} {page === 'settings' && <SettingsPage user={user} settings={settings!} subjects={subjects} records={records} table={table} onSettings={async s => { await put('settings', s); setSettings(s) }} onBackup={() => setModal('backup')} onRestore={() => setModal('restore')} onClear={() => setModal('clear')} onLogout={async () => { await logout(); setSubjects([]); setRecords([]); setTable([]) }} />}
  </main><nav className="bottom">{nav.slice(0, 5).map(([p, I, l]) => <button key={p} className={page === p ? 'active' : ''} onClick={() => navigate(p)}><I /><span>{l}</span></button>)}</nav>{toast && <div className="toast">{toast}</div>}
    {modal === 'subject' && editSubject && <SubjectForm subject={editSubject} onSave={saveSubject} onDelete={editSubject.name ? deleteSubject : undefined} onClose={() => setModal(null)} />} {modal === 'entry' && editEntry && <EntryForm entry={editEntry} subjects={subjects} onSave={saveEntry} onClose={() => setModal(null)} />} {modal === 'import' && <ImportModal uid={uid} subjects={subjects} defaultTarget={settings?.defaultTarget ?? 75} onSaved={async () => { await reload(); setModal(null); flash('Timetable imported') }} onClose={() => setModal(null)} />} {modal === 'backup' && <BackupModal data={{ version: 1, createdAt: new Date().toISOString(), account: { email: user.email ?? '', uid }, subjects, attendance: records, timetable: table, settings: settings! }} onClose={() => setModal(null)} />} {modal === 'restore' && <RestoreModal uid={uid} onDone={async () => { await reload(); setModal(null); flash('Backup restored') }} onClose={() => setModal(null)} />} {modal === 'clear' && <Modal onClose={() => setModal(null)}><h2>Clear local data?</h2><p>This removes attendance, subjects and timetable for this account from this device. Download a backup first.</p><button className="danger full" onClick={async () => { await clearUser(uid); await reload(); setModal(null); flash('Local data cleared') }}>Clear all data</button></Modal>}
  </div>
}
function Brand() { return <div className="brand"><span>✓</span><b>Self Attendance</b></div> }
function Login() { const [error, setError] = useState(''), [busy, setBusy] = useState(false); const go = async () => { setBusy(true); setError(''); try { await signIn() } catch (e) { setError(e instanceof Error ? e.message : 'Sign-in failed. Try again.') } finally { setBusy(false) } }; return <div className="login"><div className="login-card"><Brand /><div className="hero-orb">✓</div><h1>Attendance, on your terms.</h1><p>Private, fast, and stored on this device — built for the rhythm of student life.</p>{!firebaseConfigured && <div className="notice">Firebase needs configuration. Copy <code>.env.example</code> to <code>.env.local</code> and add your web app values.</div>}{error && <div className="error">{error}</div>}<button className="google full" onClick={go} disabled={busy}>{busy ? <span className="spinner" /> : <span className="g">G</span>}{busy ? 'Signing in…' : 'Continue with Google'}</button><small>We use Google only to separate your local data. Attendance never goes to Firebase.</small></div></div> }
function Profile({ user }: { user: AuthUser }) { return <div className="profile"><img src={user.photoURL ?? ''} alt="" /><div><b>{user.displayName}</b><small>{user.email}</small></div></div> }
function Dashboard({ subjects, records, table, stats, onMark, onAdd, onEdit, onNav }: { subjects: Subject[]; records: Attendance[]; table: TimetableEntry[]; stats: ReturnType<typeof overall>; onMark: (id: string, s: AttendanceStatus) => void; onAdd: () => void; onEdit: (s: Subject) => void; onNav: (p: Page) => void }) {
  const time = new Date().toTimeString().slice(0, 5), today = table.filter(t => t.day === todayDay()).sort((a, b) => a.startTime.localeCompare(b.startTime));
  const currentClass = today.find(t => t.startTime <= time && t.endTime > time), next = today.find(t => t.startTime > time);
  return <>
    <section className="grid summary"><article className="overall card"><div><p>Overall attendance</p><h2>{stats.pct.toFixed(0)}<small>%</small></h2><span>{stats.present} present · {stats.absent} absent</span></div><div className="ring" style={{ '--p': `${stats.pct}%` } as CSSProperties}><b>{stats.total}</b><small>classes</small></div></article>
      <article className="card today"><p>Today’s rhythm</p>{!today.length ? <><h3>Nothing scheduled</h3><span>Add your timetable to see class cues here.</span></> : currentClass ? <><h3>Now · {currentClass.subject}</h3><span>{currentClass.startTime}–{currentClass.endTime} · {currentClass.room || 'Room TBA'}</span>{next && <div className="next">Next: {next.subject} at {next.startTime}</div>}</> : next ? <><h3>College not started yet</h3><span>Next: {next.subject} at {next.startTime}</span></> : <><h3>College over</h3><span>Nice work — today’s classes are done.</span></>}</article>
      <article className="card action"><Sparkles /><h3>Quick start</h3><button onClick={onAdd}><Plus /> Add subject</button><button className="text" onClick={() => onNav('timetable')}>Set up timetable →</button></article></section>
    <section className="section-title"><div><h2>Your subjects</h2><p>One tap is all it takes.</p></div><button className="primary" onClick={onAdd}><Plus /> Add subject</button></section>
    {!subjects.length ? <Empty title="Start with your subjects" text="Add a subject or import your timetable, then your attendance will come to life." action="Add your first subject" onAction={onAdd} /> : <section className="subject-grid">{subjects.map(s => { const x = subjectStats(s, records); return <article className="subject card" key={s.id} style={{ '--accent': s.color } as CSSProperties}><div className="subject-top"><span className="subject-icon">{s.code.slice(0, 2) || '•'}</span><button className="more" onClick={() => onEdit(s)} aria-label={`Edit ${s.name}`}>•••</button></div><h3>{s.name}</h3><p>{s.code || 'No code'} · {s.teacher || 'Teacher not set'}</p><div className="percent"><b>{x.pct.toFixed(0)}%</b><span>{x.present} / {x.total} classes</span></div><div className="progress"><i style={{ width: `${Math.min(x.pct, 100)}%` }} /></div><small className={x.state}>{x.pct >= s.target ? `Safe to miss ${x.bunk} classes` : `Attend next ${x.required} to reach ${s.target}%`}</small><div className="mark"><button aria-label="Mark absent" className="absent" onClick={() => onMark(s.id, 'absent')}>−</button><button aria-label="Mark present" className="present" onClick={() => onMark(s.id, 'present')}><Check /> Present</button></div></article> })}</section>}
  </>
}
function AttendancePage({ subjects, records, onMark, fixedDate }: { subjects: Subject[]; records: Attendance[]; onMark: (id: string, s: AttendanceStatus) => void; fixedDate?: string }) { const [chosen, setChosen] = useState(dateISO()); const day = fixedDate ?? chosen; return <><div className="toolbar"><label>Class date<input type="date" value={day} disabled={Boolean(fixedDate)} onChange={e => setChosen(e.target.value)} /></label><span>{new Date(day + 'T12:00').toLocaleDateString(undefined, { weekday: 'long', month: 'long', day: 'numeric' })}</span></div>{!subjects.length ? <Empty title="No subjects yet" text="Add subjects from Home to start marking attendance." /> : <div className="attendance-list">{subjects.map(s => { const record = records.find(r => r.subjectId === s.id && r.date === day && r.sessionId === 'manual'); return <article className="card attendance-row" key={s.id}><span className="subject-icon" style={{ background: s.color }}>{s.code.slice(0, 2)}</span><div><h3>{s.name}</h3><small>{record ? `Marked ${record.status}` : 'Not marked'}</small></div><div className="three"><button className={record?.status === 'present' ? 'picked present' : ''} onClick={() => onMark(s.id, 'present')}>Present</button><button className={record?.status === 'absent' ? 'picked absent' : ''} onClick={() => onMark(s.id, 'absent')}>Absent</button><button className={record?.status === 'unmarked' ? 'picked' : ''} onClick={() => onMark(s.id, 'unmarked')}>Clear</button></div></article> })}</div>}</> }
function CalendarPage({ subjects, records, onMark }: { subjects: Subject[], records: Attendance[], onMark: (id: string, s: AttendanceStatus, date: string) => void }) { const [cursor, setCursor] = useState(() => new Date()), [selected, setSelected] = useState(dateISO()); const y = cursor.getFullYear(), m = cursor.getMonth(), first = new Date(y, m, 1), count = new Date(y, m + 1, 0).getDate(), offset = (first.getDay() + 6) % 7; const dates = Array.from({ length: offset + count }, (_, i) => i < offset ? '' : `${y}-${String(m + 1).padStart(2, '0')}-${String(i - offset + 1).padStart(2, '0')}`); const daily = records.filter(r => r.date === selected && r.status !== 'unmarked'); return <><div className="calendar-head"><button className="icon" onClick={() => setCursor(new Date(y, m - 1, 1))}><ChevronLeft /></button><h2>{cursor.toLocaleDateString(undefined, { month: 'long', year: 'numeric' })}</h2><button className="icon" onClick={() => setCursor(new Date(y, m + 1, 1))}><ChevronRight /></button></div><div className="week">{['M', 'T', 'W', 'T', 'F', 'S', 'S'].map((x, i) => <b key={i}>{x}</b>)}{dates.map((d, i) => d ? <button key={d} onClick={() => setSelected(d)} className={`date ${selected === d ? 'selected' : ''}`}><span>{i - offset + 1}</span><i className={records.some(r => r.date === d && r.status === 'absent') ? 'has-absent' : records.some(r => r.date === d && r.status === 'present') ? 'has-present' : ''} /></button> : <span key={i} />)}</div><section className="section-title"><div><h2>{new Date(selected + 'T12:00').toLocaleDateString(undefined, { month: 'short', day: 'numeric' })}</h2><p>{daily.filter(x => x.status === 'present').length} present · {daily.filter(x => x.status === 'absent').length} absent</p></div></section><AttendancePage subjects={subjects} records={records} fixedDate={selected} onMark={(sid, s) => onMark(sid, s, selected)} /></> }
const blankEntry = (uid: string): TimetableEntry => ({ id: id(), uid, day: 'Monday', subjectId: '', subject: '', startTime: '09:00', endTime: '10:00', room: '', teacher: '', type: 'Lecture', notes: '', order: 0 });
function TimetablePage({ subjects, table, onAdd, onEdit, onDelete, onImport }: { subjects: Subject[], table: TimetableEntry[], onAdd: () => void, onEdit: (e: TimetableEntry) => void, onDelete: (e: TimetableEntry) => void, onImport: () => void }) { const [day, setDay] = useState(todayDay()); const entries = table.filter(t => t.day === day).sort((a, b) => a.startTime.localeCompare(b.startTime)); return <><div className="toolbar"><div className="day-tabs">{DAYS.map(d => <button key={d} className={d === day ? 'active' : ''} onClick={() => setDay(d)}>{d.slice(0, 3)}</button>)}</div><button className="primary" onClick={onAdd}><Plus /> Add class</button></div><div className="import-banner"><Sparkles /><div><b>Import timetable with AI</b><span>Upload a PDF or image, then review every detected class.</span></div><button onClick={onImport}>Import</button></div>{!entries.length ? <Empty title={`No classes on ${day}`} text="Build your weekly plan manually or import a timetable." action="Import timetable" onAction={onImport} /> : <div className="timeline">{entries.map(e => <article className="card entry" key={e.id}><time>{e.startTime}<small>{e.endTime}</small></time><div><h3>{e.subject}</h3><p>{e.type} · {e.room || 'Room TBA'} {e.teacher && `· ${e.teacher}`}</p><small>{e.notes}</small></div><button className="icon" onClick={() => onEdit(e)}>•••</button><button className="icon danger-text" onClick={() => onDelete(e)}><Trash2 /></button></article>)}</div>}</> }
function Statistics({ subjects, records, stats }: { subjects: Subject[], records: Attendance[], stats: ReturnType<typeof overall> }) { const chart = subjects.map(s => ({ name: s.code || s.name.slice(0, 8), value: +subjectStats(s, records).pct.toFixed(0), fill: s.color })); const best = [...subjects].sort((a, b) => subjectStats(b, records).pct - subjectStats(a, records).pct), lowest = best[best.length - 1]; return <><section className="stat-cards"><article className="card"><p>Classes attended</p><h2>{stats.present}</h2></article><article className="card"><p>Classes missed</p><h2>{stats.absent}</h2></article><article className="card"><p>Overall</p><h2>{stats.pct.toFixed(1)}%</h2></article></section><section className="chart card"><h2>Subject attendance</h2>{chart.length ? <ResponsiveContainer width="100%" height={270}><BarChart data={chart}><XAxis dataKey="name" /><Tooltip /><Bar dataKey="value" radius={[8, 8, 0, 0]}>{chart.map(x => <Cell key={x.name} fill={x.fill} />)}</Bar></BarChart></ResponsiveContainer> : <p>Add attendance to unlock your statistics.</p>}</section><section className="grid two"><article className="card"><h3>Best subject</h3><b>{best[0]?.name || '—'}</b><p>{best[0] ? subjectStats(best[0], records).pct.toFixed(0) + '%' : 'No data yet'}</p></article><article className="card"><h3>Needs attention</h3><b>{lowest?.name || '—'}</b><p>{lowest ? subjectStats(lowest, records).pct.toFixed(0) + '%' : 'No data yet'}</p></article></section></> }
function SettingsPage({ user, settings, subjects, records, table, onSettings, onBackup, onRestore, onClear, onLogout }: { user: AuthUser, settings: Settings, subjects: Subject[], records: Attendance[], table: TimetableEntry[], onSettings: (s: Settings) => void, onBackup: () => void, onRestore: () => void, onClear: () => void, onLogout: () => void }) { return <div className="settings"><section className="card account"><img src={user.photoURL ?? ''} alt="" /><div><h2>{user.displayName}</h2><p>{user.email}</p></div><button onClick={onLogout}><LogOut /> Logout</button></section><section className="card"><h2>Attendance</h2><label>Default target percentage<input type="number" min="1" max="100" value={settings.defaultTarget} onChange={e => onSettings({ ...settings, defaultTarget: Math.max(1, Math.min(100, +e.target.value)) })} /></label><p className="muted">New subjects start with this target. Existing subjects keep their own target.</p></section><section className="card"><h2>Appearance</h2><div className="themes">{(['system', 'light', 'dark', 'amoled'] as const).map(t => <button key={t} className={settings.theme === t ? 'picked' : ''} onClick={() => onSettings({ ...settings, theme: t })}>{t === 'amoled' ? <Moon /> : null}{t}</button>)}</div></section><section className="card"><h2>Your data</h2><p className="muted">Your attendance stays in IndexedDB on this device. Only the timetable file you select is sent to Gemini during AI import.</p><div className="data-actions"><button onClick={onBackup}><Download /> Backup data</button><button onClick={onRestore}><Upload /> Restore backup</button><button className="danger-text" onClick={onClear}><Trash2 /> Clear local data</button></div></section><section className="card about"><h2>Self Attendance <small>v1.0.0</small></h2><p>{subjects.length} subjects · {records.length} attendance records · {table.length} timetable sessions</p><p className="muted">Local-first by design. Sign in only identifies your separate device dataset; attendance is never uploaded to Firebase.</p></section></div> }
function SubjectForm({ subject, onSave, onDelete, onClose }: { subject: Subject, onSave: (s: Subject) => void, onDelete?: (s: Subject, history: boolean) => void, onClose: () => void }) { const [s, setS] = useState(subject); const valid = s.name.trim() && s.target > 0 && s.target <= 100; return <Modal onClose={onClose}><h2>{subject.name ? 'Edit subject' : 'New subject'}</h2><form onSubmit={e => { e.preventDefault(); if (valid) onSave(s) }}><label>Subject name<input required value={s.name} onChange={e => setS({ ...s, name: e.target.value })} placeholder="e.g. Data Structures" /></label><div className="form-grid"><label>Short code<input value={s.code} onChange={e => setS({ ...s, code: e.target.value })} placeholder="CS201" /></label><label>Target %<input required type="number" min="1" max="100" value={s.target} onChange={e => setS({ ...s, target: +e.target.value })} /></label></div><label>Teacher<input value={s.teacher} onChange={e => setS({ ...s, teacher: e.target.value })} /></label><label>Room<input value={s.room} onChange={e => setS({ ...s, room: e.target.value })} /></label><label>Color<input type="color" value={s.color} onChange={e => setS({ ...s, color: e.target.value })} /></label><button className="primary full" disabled={!valid}>Save subject</button></form>{onDelete && <div className="delete-subject"><button className="danger" onClick={() => onDelete(s, false)}>Delete subject, keep history</button><button className="danger-text" onClick={() => onDelete(s, true)}>Delete subject & history</button></div>}</Modal> }
function EntryForm({ entry, subjects, onSave, onClose }: { entry: TimetableEntry, subjects: Subject[], onSave: (e: TimetableEntry) => void, onClose: () => void }) { const [e, setE] = useState(entry); const choose = (v: string) => { const s = subjects.find(x => x.id === v); setE({ ...e, subjectId: v, subject: s?.name ?? e.subject, teacher: s?.teacher ?? e.teacher, room: s?.room ?? e.room }) }; return <Modal onClose={onClose}><h2>{entry.subject ? 'Edit class' : 'New class'}</h2><form onSubmit={x => { x.preventDefault(); if (e.subject.trim() && e.startTime < e.endTime) onSave(e) }}><label>Day<select value={e.day} onChange={x => setE({ ...e, day: x.target.value })}>{DAYS.map(d => <option key={d}>{d}</option>)}</select></label><label>Subject<select value={e.subjectId} onChange={x => choose(x.target.value)}><option value="">Custom / type below</option>{subjects.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Subject name<input required value={e.subject} onChange={x => setE({ ...e, subject: x.target.value })} /></label><div className="form-grid"><label>Start<input required type="time" value={e.startTime} onChange={x => setE({ ...e, startTime: x.target.value })} /></label><label>End<input required type="time" value={e.endTime} onChange={x => setE({ ...e, endTime: x.target.value })} /></label></div><div className="form-grid"><label>Room<input value={e.room} onChange={x => setE({ ...e, room: x.target.value })} /></label><label>Class type<select value={e.type} onChange={x => setE({ ...e, type: x.target.value })}><option>Lecture</option><option>Lab</option><option>Tutorial</option><option>Seminar</option></select></label></div><label>Teacher<input value={e.teacher} onChange={x => setE({ ...e, teacher: x.target.value })} /></label><label>Notes<input value={e.notes} onChange={x => setE({ ...e, notes: x.target.value })} /></label><button className="primary full">Save class</button></form></Modal> }
function ImportModal({ uid, subjects, defaultTarget, onSaved, onClose }: { uid: string, subjects: Subject[], defaultTarget: number, onSaved: () => void, onClose: () => void }) {
  const [file, setFile] = useState<File | null>(null), [items, setItems] = useState<Partial<TimetableEntry>[]>([]), [busy, setBusy] = useState(false), [error, setError] = useState(''); const choose = async (f?: File) => { if (!f) return; setFile(f); setBusy(true); setError(''); try { setItems(await extractTimetable(f)) } catch (e) { setError(e instanceof Error ? e.message : 'Unable to import this timetable.') } finally { setBusy(false) } }; const edit = (i: number, k: string, v: string) => setItems(items.map((x, n) => n === i ? { ...x, [k]: v } : x)); const commit = async () => {
    // 1. Collect valid entries
    const valid = items.filter(x => x.day && x.subject?.trim() && x.startTime && x.endTime);
    if (!valid.length) return;

    // 2. Collect unique subject names (case-insensitive, trimmed)
    const uniqueNames = new Map<string, string>(); // normalized -> original first-seen name
    for (const x of valid) { const name = x.subject!.trim(); const key = name.toLowerCase(); if (!uniqueNames.has(key)) uniqueNames.set(key, name) }

    // 3. Build a lookup: normalized name -> Subject (existing or newly created)
    const subjectLookup = new Map<string, Subject>();

    // Check existing subjects first
    for (const s of subjects) { const key = s.name.trim().toLowerCase(); if (uniqueNames.has(key)) subjectLookup.set(key, s) }

    // Create new subjects for names not found in existing subjects
    let colorIdx = subjects.length;
    const newSubjects: Subject[] = [];
    for (const [key, name] of uniqueNames) {
      if (subjectLookup.has(key)) continue;
      // Find the first timetable entry for this subject to extract metadata
      const sample = valid.find(x => x.subject!.trim().toLowerCase() === key);
      const subj: Subject = {
        id: id(), uid,
        name,
        code: (sample as Record<string, string>)?.subjectCode ?? '',
        teacher: sample?.teacher ?? '',
        room: sample?.room ?? '',
        color: colors[colorIdx % colors.length],
        target: defaultTarget,
        createdAt: new Date().toISOString()
      };
      colorIdx++;
      subjectLookup.set(key, subj);
      newSubjects.push(subj);
    }

    // 4. Save new subjects to IndexedDB
    for (const s of newSubjects) await put('subjects', s);

    // 5. Save timetable entries with correct subjectIds
    for (const x of valid) {
      const key = x.subject!.trim().toLowerCase();
      const matched = subjectLookup.get(key);
      await put('timetable', { ...blankEntry(uid), ...x, id: id(), uid, subjectId: matched?.id ?? '', subject: x.subject!.trim(), day: x.day!, startTime: x.startTime!, endTime: x.endTime!, room: x.room ?? '', teacher: x.teacher ?? '', type: x.type || 'Lecture', notes: x.notes ?? '', order: 0 });
    }

    onSaved();
  }; return <Modal onClose={onClose}><h2><Sparkles /> Import timetable with AI</h2><p className="muted">Only this selected timetable file is sent to Gemini. Review before anything is saved.</p><label className="drop"><CloudUpload /><b>{file ? file.name : 'Upload timetable'}</b><span>PDF, PNG, JPG, JPEG or WEBP · max 15 MB</span><input type="file" accept="application/pdf,image/png,image/jpeg,image/webp" onChange={e => choose(e.target.files?.[0])} /></label>{busy && <div className="processing"><span className="spinner" /> Reading your timetable…</div>}{error && <div className="error">{error}</div>}{items.length > 0 && <><div className="success"><Check /> AI detected {items.length} timetable entries. Edit anything uncertain.</div><div className="review">{items.map((x, i) => <div key={i} className="review-row"><select value={x.day || 'Monday'} onChange={e => edit(i, 'day', e.target.value)}>{DAYS.map(d => <option key={d}>{d}</option>)}</select><input value={x.subject || ''} onChange={e => edit(i, 'subject', e.target.value)} placeholder="Subject" /><input type="time" value={x.startTime || ''} onChange={e => edit(i, 'startTime', e.target.value)} /><input type="time" value={x.endTime || ''} onChange={e => edit(i, 'endTime', e.target.value)} /><input value={x.room || ''} onChange={e => edit(i, 'room', e.target.value)} placeholder="Room" /><button className="icon danger-text" onClick={() => setItems(items.filter((_, n) => n !== i))}><Trash2 /></button></div>)}</div><button className="primary full" onClick={commit}>Import {items.length} timetable entries</button></>}</Modal>
}

function BackupModal({ data, onClose }: { data: BackupPayload, onClose: () => void }) { const download = () => { const blob = new Blob([makeBackup(data)], { type: 'text/plain' }), url = URL.createObjectURL(blob), a = document.createElement('a'); a.href = url; a.download = `self-attendance-backup-${data.createdAt.slice(0, 10)}.txt`; a.click(); URL.revokeObjectURL(url) }; return <Modal onClose={onClose}><h2>Backup your data</h2><p>Your backup is readable text with a protected structured section for reliable restore. Store it somewhere safe.</p><ul><li>{data.subjects.length} subjects</li><li>{data.attendance.length} attendance records</li><li>{data.timetable.length} timetable sessions</li></ul><button className="primary full" onClick={download}><Download /> Download backup (.txt)</button></Modal> }
function RestoreModal({ uid, onDone, onClose }: { uid: string, onDone: () => void, onClose: () => void }) { const [data, setData] = useState<BackupPayload | null>(null), [error, setError] = useState(''), [mode, setMode] = useState<'merge' | 'replace'>('merge'); const input = useRef<HTMLInputElement>(null); const choose = async (f?: File) => { if (!f) return; try { setError(''); setData(parseBackup(await f.text())) } catch (e) { setData(null); setError(e instanceof Error ? e.message : 'Could not read that backup.') } }; return <Modal onClose={onClose}><h2>Restore backup</h2><p>Nothing changes until you confirm.</p><input ref={input} type="file" accept="text/plain,.txt" onChange={e => choose(e.target.files?.[0])} />{error && <div className="error">{error}</div>}{data && <><div className="success"><Check /> Found {data.subjects.length} subjects, {data.attendance.length} attendance records, and {data.timetable.length} timetable entries.</div><label className="choice"><input type="radio" checked={mode === 'merge'} onChange={() => setMode('merge')} /> Merge with existing data</label><label className="choice"><input type="radio" checked={mode === 'replace'} onChange={() => setMode('replace')} /> Replace existing data</label><button className="primary full" onClick={async () => { await restore(uid, data, mode === 'replace'); onDone() }}>Confirm restore</button></>}</Modal> }
function Empty({ title, text, action, onAction }: { title: string, text: string, action?: string, onAction?: () => void }) { return <section className="empty card"><BookOpen /><h2>{title}</h2><p>{text}</p>{action && <button className="primary" onClick={onAction}>{action}</button>}</section> }
export default App;
